version: '3'

services:
  mysql-standalone-container:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
    volumes:
      - /data/mysql
  tax-service-container:
    image: tax-service:1
    ports:
      - "8084:8084"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone-container
    volumes:
      - /data/tax-service